services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: questiongame_db
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "question_game_db"
    volumes:
      - db_vol:/var/lib/mysql
    # network_mode: "host"

volumes:
  db_vol:
    driver: local
